apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: argocd-webhook
  namespace: argo-events
spec:
  eventBusName: default
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    argocd-sync-failed:
      endpoint: /sync-failed
      method: POST
      port: "12000"