apiVersion: "ingress.oraclecloud.com/v1beta1"
kind: IngressClassParameters
metadata:
  name: native-ic-params
spec:
  compartmentId: "ocid1.compartment"
  subnetId: "ocid1.subnet"
  loadBalancerName: "ec-service-test-lb"
  isPrivate: false
  maxBandwidthMbps: 100
  minBandwidthMbps: 10
